config/routes.rb
Rails.application.routes.draw do
  resources :categories do
    resources :tasks
  end

  root 'categories#index'
  # get 'categories' => 'categories#index'
  # get 'categories/:id', to: 'categories#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: { case_sensitive: false }
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category
  
  validates :name, presence: true
  validates :name, uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      redirect_to @category
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # def destroy
  #   @category = Category.find(params[:id])
  #   if @category.destroy
  #     redirect_to categories_path
  #   else
  #     render :index
  #   end
  # end

  private

  def category_params
    params.require(:category).permit(:name, :body)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  
  def index
    @category_id = params[:category_id]
    @tasks = Category.find(params[:category_id]).tasks
    # @tasks = @category.tasks
  end

  def new
    @task = @category.tasks.build
  end

  def create
    @task = @category.tasks.build(task_params) # papasahan na ng params

    if @task.save
      redirect_to category_tasks_path # galing sa rails/info which is yung indextasks
    else
      render :new
    end
  end

  def task_params
    params.require(:task).permit(:name, :body, :deadline, :status, :category_id) # need pa rin isama si :category_id kasi hahanapin ata ni rails itong parameter
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_form.html.erb
<%= form_with model: category do |form| %>
  <% category.errors.full_messages_for(:name).each do |message| %>
    <div><%= message %></div>
  <% end %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1> Edit Category </h1>

<%= render "form", category: @category %>
<%= link_to "back", category_path(@category) %>

app/views/categories/index.html.erb
<h1>Categories</h1>

<table>
  <tr>
    <td>Category Name</td>
    <td>Category Body</td>
  </tr>

  <%@categories.each do |category| %>
    <tr>
      <td><%= link_to category.name, category %></td>
      <td><%= category.body %></td>
    </tr>
    <%end%>
</table>

<%= link_to "new category", new_category_path %>

app/views/categories/new.html.erb
<h1> New Category </h1>

<%= render "form", category: @category %>
<%= link_to "back", categories_path %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<p><%= @category.body %></p>
<%= link_to "edit", edit_category_path(@category) %> <br>
<%= link_to "back", categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JournalApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<div>
<table>
  <thead>
    <tr>
      <th>TASK NAME</th>
      <th>TASK DESCRIPTION</th>
      <th>DEADLINE</th>
      <th>STATUS</th>
      <th>CREATED AT</th>
    </tr>
  </thead>

  <tbody>
  
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.body %></td>
        <td><%= task.deadline %></td>
        <td><%= task.status %></td>
        <td><%= task.created_at %></td>
      </tr>
    <%end%>

  </tbody>
</table>

  <button type="button"><%= link_to 'Back', category_path(@category_id) %></button>

</div>